const adjective = [
  'admiring',
  'adoring',
  'affectionate',
  'agitated',
  'amazing',
  'angry',
  'awesome',
  'beautiful',
  'blissful',
  'bold',
  'boring',
  'brave',
  'busy',
  'charming',
  'clever',
  'cool',
  'compassionate',
  'competent',
  'condescending',
  'confident',
  'cranky',
  'crazy',
  'dazzling',
  'determined',
  'distracted',
  'dreamy',
  'eager',
  'ecstatic',
  'elastic',
  'elated',
  'elegant',
  'eloquent',
  'epic',
  'exciting',
  'fervent',
  'festive',
  'flamboyant',
  'focused',
  'friendly',
  'frosty',
  'funny',
  'gallant',
  'gifted',
  'goofy',
  'gracious',
  'great',
  'happy',
  'hardcore',
  'heuristic',
  'hopeful',
  'hungry',
  'infallible',
  'inspiring',
  'intelligent',
  'interesting',
  'jolly',
  'jovial',
  'keen',
  'kind',
  'laughing',
  'loving',
  'lucid',
  'magical',
  'mystifying',
  'modest',
  'musing',
  'naughty',
  'nervous',
  'nice',
  'nifty',
  'nostalgic',
  'objective',
  'optimistic',
  'peaceful',
  'pedantic',
  'pensive',
  'practical',
  'priceless',
  'quirky',
  'quizzical',
  'recursing',
  'relaxed',
  'reverent',
  'romantic',
  'sad',
  'serene',
  'sharp',
  'silly',
  'sleepy',
  'stoic',
  'strange',
  'stupefied',
  'suspicious',
  'sweet',
  'tender',
  'thirsty',
  'trusting',
  'unruffled',
  'upbeat',
  'vibrant',
  'vigilant',
  'vigorous',
  'wizardly',
  'wonderful',
  'xenodochial',
  'youthful',
  'zealous',
  'zen',
]

const surname = [
  'agnesi',
  'albattani',
  'allen',
  'almeida',
  'antonelli',
  'archimedes',
  'ardinghelli',
  'aryabhata',
  'austin',
  'babbage',
  'banach',
  'banzai',
  'bardeen',
  'bartik',
  'bassi',
  'beaver',
  'bell',
  'benz',
  'bhabha',
  'bhaskara',
  'black',
  'blackburn',
  'blackwell',
  'bohr',
  'booth',
  'borg',
  'bose',
  'bouman',
  'boyd',
  'brahmagupta',
  'brattain',
  'brown',
  'buck',
  'burnell',
  'cannon',
  'carson',
  'cartwright',
  'carver',
  'cerf',
  'chandrasekhar',
  'chaplygin',
  'chatelet',
  'chatterjee',
  'chaum',
  'chebyshev',
  'clarke',
  'cohen',
  'colden',
  'cori',
  'cray',
  'curran',
  'curie',
  'darwin',
  'davinci',
  'dewdney',
  'dhawan',
  'diffie',
  'dijkstra',
  'dirac',
  'driscoll',
  'dubinsky',
  'easley',
  'edison',
  'einstein',
  'elbakyan',
  'elgamal',
  'elion',
  'ellis',
  'engelbart',
  'euclid',
  'euler',
  'faraday',
  'feistel',
  'fermat',
  'fermi',
  'feynman',
  'franklin',
  'gagarin',
  'galileo',
  'galois',
  'ganguly',
  'gates',
  'gauss',
  'germain',
  'goldberg',
  'goldstine',
  'goldwasser',
  'golick',
  'goodall',
  'gould',
  'greider',
  'grothendieck',
  'haibt',
  'hamilton',
  'haslett',
  'hawking',
  'hellman',
  'heisenberg',
  'hermann',
  'herschel',
  'hertz',
  'heyrovsky',
  'hodgkin',
  'hofstadter',
  'hoover',
  'hopper',
  'hugle',
  'hypatia',
  'ishizaka',
  'jackson',
  'jang',
  'jemison',
  'jennings',
  'jepsen',
  'johnson',
  'joliot',
  'jones',
  'kalam',
  'kapitsa',
  'kare',
  'keldysh',
  'keller',
  'kepler',
  'khayyam',
  'khorana',
  'kilby',
  'kirch',
  'knuth',
  'kowalevski',
  'lalande',
  'lamarr',
  'lamport',
  'leakey',
  'leavitt',
  'lederberg',
  'lehmann',
  'lewin',
  'lichterman',
  'liskov',
  'lovelace',
  'lumiere',
  'mahavira',
  'margulis',
  'matsumoto',
  'maxwell',
  'mayer',
  'mccarthy',
  'mcclintock',
  'mclaren',
  'mclean',
  'mcnulty',
  'mendel',
  'mendeleev',
  'meitner',
  'meninsky',
  'merkle',
  'mestorf',
  'mirzakhani',
  'montalcini',
  'moore',
  'morse',
  'murdock',
  'moser',
  'napier',
  'nash',
  'neumann',
  'newton',
  'nightingale',
  'nobel',
  'noether',
  'northcutt',
  'noyce',
  'panini',
  'pare',
  'pascal',
  'pasteur',
  'payne',
  'perlman',
  'pike',
  'poincare',
  'poitras',
  'proskuriakova',
  'ptolemy',
  'raman',
  'ramanujan',
  'ride',
  'ritchie',
  'rhodes',
  'robinson',
  'roentgen',
  'rosalind',
  'rubin',
  'saha',
  'sammet',
  'sanderson',
  'satoshi',
  'shamir',
  'shannon',
  'shaw',
  'shirley',
  'shockley',
  'shtern',
  'sinoussi',
  'snyder',
  'solomon',
  'spence',
  'stonebraker',
  'sutherland',
  'swanson',
  'swartz',
  'swirles',
  'taussig',
  'tereshkova',
  'tesla',
  'tharp',
  'thompson',
  'torvalds',
  'tu',
  'turing',
  'varahamihira',
  'vaughan',
  'villani',
  'visvesvaraya',
  'volhard',
  'wescoff',
  'wilbur',
  'wiles',
  'williams',
  'williamson',
  'wilson',
  'wing',
  'wozniak',
  'wright',
  'wu',
  'yalow',
  'yonath',
  'zhukovsky',
]

function capitalize(s: string) {
  return s.slice(0, 1).toUpperCase() + s.slice(1)
}

function validateEthereumAddress(address: string): string {
  // Remove '0x' prefix if present
  const cleanAddress = address.toLowerCase().replace(/^0x/, '')

  // Validate: must be exactly 40 hexadecimal characters
  if (!/^[0-9a-f]{40}$/.test(cleanAddress)) {
    throw new Error(
      `Invalid Ethereum address format: ${address}. Expected 40 hex characters with optional 0x prefix.`,
    )
  }

  return cleanAddress
}

function addressToRandomNumbers(address: string): [number, number] {
  // Validate and clean the address
  const cleanAddress = validateEthereumAddress(address)

  // Take 13 hex chars (52 bits) for each number - safely within JavaScript's 53-bit integer range
  // 13 hex chars = 52 bits < 53 bits (safe integer range)
  const firstSegment = cleanAddress.slice(0, 13)
  const secondSegment = cleanAddress.slice(13, 26)

  // Maximum value for 13 hex digits (all F's)
  const maxValue = 0xfffffffffffff // 2^52 - 1

  // Convert hex to decimal and normalize to [0, 1) range
  const num1 = parseInt(firstSegment, 16) / maxValue
  const num2 = parseInt(secondSegment, 16) / maxValue

  return [num1, num2]
}

export function generateDockerName(ethereumAddress?: string) {
  let random1: number
  let random2: number

  if (ethereumAddress) {
    ;[random1, random2] = addressToRandomNumbers(ethereumAddress)
  } else {
    random1 = Math.random()
    random2 = Math.random()
  }

  return (
    capitalize(adjective[Math.floor(random1 * adjective.length)]) +
    ' ' +
    capitalize(surname[Math.floor(random2 * surname.length)])
  )
}
